### PR TITLE
Update ext-maven-pr-build.yml

### PR DESCRIPTION
**Pull request by shroffk**
Explicitly adding jdk version

P.S. hope I am doing this write

### CODE REVIEW

**Comment by shroffk** [comment]
@ralphlange

**Comment by ralphlange** [comment]
No need to mention - owners get PR notifications.
Will look at it tomorrow.

**Comment by shroffk** [comment]
I do apologize for the excessive mentions.

**Comment by ralphlange** [comment]
This change makes no sense.
See https://docs.openstack.org/infra/jenkins-job-builder/ for the documentation of Jenkins Job Builder.
The fact that a project is Java code is defined in the Maven POM, not in the Jenkins job.
The yaml tags used in this PR are not defined for JJB.

**Comment by ralphlange** [comment]
My bad, sorry. This is about the JDK that is used to run Maven, not the Maven configuration about what Java version to use.
Still, the PR does not make sense. Configuration of this property is part of the CloudBees DEV@Cloud Jenkins plugin configuration. I will create a separate PR with the necessary change.

**Comment by ralphlange** [comment]
`language` is not defined for JJB at job level, `jdk` is.
However, the correct value for CloudBees Jenkins seems to be 'Oracle JDK 8 (latest)' - at least that's what appears in the job XML after manually setting the option. (You can see the XML by replacing the trailing `/configure` in the Jenkins URL with `/config.xml`.)

**Comment by shroffk** [comment]
omg...my bad I used the travis keywords.
However, the change here is to configure the container jdk which is what you pointed out

**Comment by ralphlange** [comment]
I am about to check if  `jdk: 'Oracle JDK 8 (latest)'` is doing the job. Was not able / inclined to do that from home on the weekend.

**Comment by ralphlange** [comment]
Done.
All existing Java jobs in https://openepics.ci.cloudbees.com/view/EPICS%20V4%20Java/
have been updated to use `jdk: 'Oracle JDK 8 (latest)'`. Check on the website shows that it worked.

**Pull request closed without merging**
